### ISSUE TITLE
How to use this exporter inside maven project

### ISSUE THREAD

**Issue by theghost5800** [dynatrace-oss/opentelemetry-metric-java#25]
**Describe the bug**
Our project is maven based and we are using already Dynatrace in CloudFoundry environment. I am looking to use [OpenTelemetry metrics feature](https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-metrics) but I am not sure how I can use dynatrace exporter inside maven project. 

Another question is after we manage to add this dynatrace exporter to the application, is it still necessary to use opentelemetry agent to send metrics to Dynatrace or this is not necessary when we have OneAgent included?

**Additional information about the project:**
Our application is java web application which is running on CloudFoundry, it uses "java_buildpack" to inject Dynatrace OneAgent into the environment and send metrics to Dynatrace environment.

**Comment by arminru** [comment]
Hey @theghost5800!

We have not published the package to Maven Central but in the releases section you can find the JARs to include in your project: https://github.com/dynatrace-oss/opentelemetry-metric-java/releases

On your second question: Can you please elaborate on what you mean by the OpenTelemetry agent?
Certain metrics are collected by the Dynatrace OneAgent itself from your Java application but if you want to ingest your application metrics created by an OpenTelemetry-based instrumentation, then you'll have to export them using this exporter here or you use an OpenTelemetry Collector that can export them to Dynatrace as well.

**Comment by arminru** [comment]
I hope the answer above was sufficient. Otherwise you could also consider moving from this exporter package to the generic OTel OTLP metrics exporter, as Dynatrace supports ingesting OTLP metrics directly as well now. You can find more information here:

- https://www.dynatrace.com/support/help/shortlink/send-metrics-via-otlp-exporter
- https://www.dynatrace.com/support/help/shortlink/api-otlp-metrics-ingest
- https://www.dynatrace.com/support/help/shortlink/opent-java-metrics
