### ISSUE TITLE
How to use this with auto instrumentation with opentelemetry-javaagent

### ISSUE THREAD

**Issue by a1tan** [dynatrace-oss/opentelemetry-metric-java#26]
We are using auto instrumentation to instrument our metrics by using [opentelemetry-javaagent.](https://opentelemetry.io/docs/instrumentation/java/automatic/) I couldn't find the documentation for that or I did not notice the related part. What is the correct way to use this exporter along with auto instrumentation with javaagent?

**Comment by arminru** [comment]
Hi @a1tan!

The OTel Java auto instrumentation comes with a built-in OTLP metrics exporter, which can be configured as shown here:
https://github.com/open-telemetry/opentelemetry-java/blob/v1.21.0/sdk-extensions/autoconfigure/README.md#exporters

You could consider using this one instead of the separate exporter package provided by this repository, as Dynatrace supports ingesting OTLP metrics directly as well.

You can find more information on ingesting OTel metrics via OTLP here:

- https://www.dynatrace.com/support/help/shortlink/send-metrics-via-otlp-exporter
- https://www.dynatrace.com/support/help/shortlink/api-otlp-metrics-ingest
- https://www.dynatrace.com/support/help/shortlink/opent-java-metrics#send

The OTLP exporter should be set by default by the OTel Java auto instrumentation, so you should only need to specify the endpoint URL and headers (`Authorization="Api-Token <TOKEN>"`) as mentioned in the docs above.

**Comment by a1tan** [comment]
Thank you @arminru for the answer, it is more clear for me now.

**Comment by arminru** [comment]
Great, thanks for the response!
